import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import SVGIMG from "../../public/logo.svg";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const inter = Inter({ subsets: ["latin"] });
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${inter.className} antialiased min-h-screen flex items-center p-4 flex-col h-screen`}
      >
        <header className="flex items-center justify-center h-24 w-full flex-col gap-4">
          <Link href="/">
            <Image src={SVGIMG} alt="Logo" className="w-32" />
          </Link>
        </header>
        <main className="h-full flex items-center flex-col max-w-xl w-full">
          {children}
        </main>
      </body>
    </html>
  );
}
